export const FETCH_COLLABORATORS = "FETCH_COLLABORATORS";
export const FETCH_QUALIFICATIONS = "FETCH_QUALIFICATIONS";
export const FETCH_COURSES = "FETCH_COURSES";
export const FETCH_SINGLE_COLLABORATOR = "FETCH_SINGLE_COLLABORATOR";
