export const FETCH_COLLABORATORS = "FETCH_COLLABORATORS";
export const FETCH_QUALIFICATIONS = "FETCH_QUALIFICATIONS";
export const FETCH_COURSES = "FETCH_COURSES";
export const FETCH_SINGLE_COLLABORATOR = "FETCH_SINGLE_COLLABORATOR";
export const FETCH_COLLABORATORS_INFOS = "FETCH_COLLABORATORS_INFOS";
export const FETCH_QUALIFICATIONS_OF_COLLABORATOR =
  "FETCH_QUALIFICATIONS_OF_COLLABORATOR";
export const FETCH_COURSES_INFOS = "FETCH_COURSES_INFOS";

export const ADD_COURSE = "ADD_COURSE";
export const ADD_COURSE_TO_HISTORY = "ADD_COURSE_TO_HISTORY";
export const ADD_COURSE_TO_NECESSARY = "ADD_COURSE_TO_NECESSARY";
export const ADD_QUALIFICATION_TO_COLLABORATOR =
  "ADD_QUALIFICATION_TO_COLLABORATOR";

export const DELETE_COURSE = "DELETE_COURSE";
export const DELETE_COURSE_FROM_HISTORY = "DELETE_COURSE_FROM_HISTORY";
export const DELETE_COURSE_FROM_NECESSARY = "DELETE_COURSE_FROM_NECESSARY";

export const REMOVE_QUALIFICATIONS_FROM_COLLABORATOR =
  "REMOVE_QUALIFICATIONS_FROM_COLLABORATOR";
