export const FETCH_COLLABORATORS = "FETCH_COLLABORATORS";
export const FETCH_QUALIFICATIONS = "FETCH_QUALIFICATIONS";
export const FETCH_COURSES = "FETCH_COURSES";
export const FETCH_SINGLE_COLLABORATOR = "FETCH_SINGLE_COLLABORATOR";
export const FETCH_COLLABORATORS_INFOS = "FETCH_COLLABORATORS_INFOS";

export const ADD_COURSE = "ADD_COURSE";

export const DELETE_COURSE = "DELETE_COURSE";

export const FETCH_QUALIFICATIONS_INFOS = "FETCH_QUALIFICATIONS_INFOS";
export const FETCH_COURSES_INFOS = "FETCH_COURSES_INFOS";
